### ISSUE TITLE
Confusing icon

### ISSUE THREAD

**Issue by RobH123** [friendsofagape/autographa-lite#50] opened 2018-09-04 00:17 UTC
In v1.2.1 on Ubuntu, scrolling over icon of quill on scroll (top left of main window) changes the pointer to a hand (implying a clickable link), but clicking seems to have no effect.

**Comment by joelthe1** [comment] 2018-09-04 07:50
Thanks for pointing this out. We'll add this to our next release which should be soon.

**Comment by joelthe1** [comment] 2018-09-08 07:37
The issue is fixed in v1.2.2. Thanks again!

**Closed by joelthe1** 2018-09-08 07:37 UTC
Labels: bug, good first issue
